# Bench Core Chip (benchmark only)

chip:
  id: bench_core
  name: Benchmark Core Intelligence
  version: 0.1.0
  activation: opt_in
  description: |
    Lightweight chip for benchmarking methodology variants.
    Captures generic tool and prompt signals without domain assumptions.
  author: Vibeship
  license: MIT
  human_benefit: "Enable safe evaluation of chip learning methodologies."
  harm_avoidance:
    - "No deceptive or manipulative insights"
  risk_level: low
  safety_tests:
    - "no_harmful_content"
  domains:
    - benchmarking
    - tooling
    - workflow

triggers:
  events:
    - "pre_tool"
    - "post_tool"
    - "post_tool_failure"
    - "user_prompt"
    - "PreToolUse"
    - "PostToolUse"
    - "PostToolUseFailure"
    - "UserPromptSubmit"
  patterns:
    - "tool"
    - "command"
    - "file"
    - "prompt"

observers:
  - name: tool_event
    description: Captures generic tool activity
    triggers: ["tool", "command", "file", "write", "edit", "bash"]
    capture:
      required: {}
      optional:
        tool_name: "Tool name"
        file_path: "File path (if any)"
        command: "Command (if any)"
        cwd: "Working directory"
        status: "Outcome status (success/failure)"
        error: "Error message (if any)"
    extraction:
      - field: status
        keywords:
          success: ["succeeded", "success", "completed", "ok"]
          failure: ["failed", "error", "exception"]

  - name: user_prompt
    description: Captures user prompts for preference signals
    triggers: ["user", "prompt", "prefer", "rather", "instead", "why"]
    capture:
      required: {}
      optional:
        text: "Prompt text"
        message: "Prompt message"
        content: "Prompt content"
        status: "Outcome status (success/failure)"
    extraction:
      - field: status
        keywords:
          success: ["works", "worked", "perfect", "great"]
          failure: ["no", "not", "wrong"]

  - name: pre_tool_event
    description: Captures generic pre-tool context
    triggers: ["pre_tool", "PreToolUse"]
    capture:
      required: {}
      optional:
        tool_name: Tool name
        command: Command (if any)
        cwd: Working directory
        file_path: File path (if any)
        session_id: Session identifier
        event_type: Normalized event type

  - name: post_tool_event
    description: Captures generic post-tool context
    triggers: ["post_tool", "PostToolUse"]
    capture:
      required: {}
      optional:
        tool_name: Tool name
        command: Command (if any)
        cwd: Working directory
        file_path: File path (if any)
        status: Outcome status
        success: Success signal
        duration_ms: Execution time
        event_type: Normalized event type
    extraction:
      - field: status
        keywords:
          success: ["succeeded", "success", "completed", "ok"]
          failure: ["failed", "error", "exception"]

  - name: tool_failure
    description: Captures generic tool failures
    triggers: ["post_tool_failure", "PostToolUseFailure", "failed", "error"]
    capture:
      required: {}
      optional:
        tool_name: Tool name
        command: Command (if any)
        cwd: Working directory
        error: Error message
        status: Outcome status
        event_type: Normalized event type
    extraction:
      - field: status
        keywords:
          failure: ["failed", "error", "exception"]

outcomes:
  positive:
    - condition: "success == true"
      insight: "Tool operation succeeded"
      weight: 0.8
    - condition: "status == success"
      insight: "User/tool signaled success"
      weight: 1.0
  negative:
    - condition: "status == failure"
      insight: "Tool operation failed"
      weight: 0.8
    - condition: "error"
      insight: "User/tool signaled failure"
      weight: 1.0
